# Generated by Django 4.2.4 on 2023-08-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0002_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nevisande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('nevisande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybook.book')),
            ],
        ),
    ]
