# Generated by Django 4.2.4 on 2023-08-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0003_nevisande'),
    ]

    operations = [
        migrations.AddField(
            model_name='nevisande',
            name='ketab',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
