# Generated by Django 4.2.4 on 2023-08-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0004_nevisande_ketab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nevisande',
            old_name='ketab',
            new_name='book_author',
        ),
    ]
