# Generated by Django 4.2.4 on 2023-08-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0005_rename_ketab_nevisande_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nevisande',
            old_name='book_author',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='nevisande',
            name='nevisande',
        ),
        migrations.RemoveField(
            model_name='nevisande',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='book',
            name='nevisande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mybook.nevisande'),
        ),
    ]
