# Generated by Django 4.2.4 on 2023-08-24 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0006_rename_book_author_nevisande_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nevisande',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
