# Generated by Django 4.2.4 on 2023-10-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='mybook.category'),
        ),
    ]
